name: Deployment Exercise 1
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
        working-directory: ./o4 PRACTICE PROJECT
      - name: Lint
        run: npm run Lint
        working-directory: ./o4 PRACTICE PROJECT
      - name: Test code
        run: npm run Test
        working-directory: ./o4 PRACTICE PROJECT
      - name: Build code
        run: npm run Build
        working-directory: ./o4 PRACTICE PROJECT
      - name: Deploy code
        run: echo "Deploying ..."